Bugfix: failed grant requests can be cancelled
common-fate/glide pull request #278
Opened 2022-09-28 00:41 UTC by meyerjrr

2022-09-28 06:11 UTC, JoshuaWilkes commented
@meyerjrr 

I think that the root cause of the request showing up in "upcoming" when the grant has failed is because we don't correctly handle setting the value of the end time that is used to list requests in either upcoming or past.

see this method

```
func (r *Request) DDBKeys() (ddb.Keys, error) {
	// - APPROVED requests have an end time on the grant
	// - PENDING Scheduled requests have a request end time
	// - PENDING asap requests should have MAXIMUM endtime
	// - Declined and Cancelled requests should have an end time = createdAt so they get a somewhat natural order in the results
	// - REVOKED grants should have end time = created at
	end := r.CreatedAt
	if r.Status == APPROVED || r.Status == PENDING {
		if r.Grant != nil {
			if r.Grant.Status != ac_types.GrantStatusREVOKED {
				end = r.Grant.End
			}
		} else if r.IsScheduled() {
			_, end = r.GetInterval()
		} else {
			// maximum time value in Go
			// this means that asap requests which are not approved will always be the first in results because the end time in unknown until approval
			end = time.Unix(1<<63-1, 0)
		}
	}

```

This in in pkg/access/request.go

What should happen here is that if the grant is not nil and the grant status is failed/error it should set the end = r.createdAt this means that the request will move into the "past" column as soon as the grant fails.

This way the UI will show the request as Error and it will be in the past column as expected.

2022-09-28 23:39 UTC, JoshuaWilkes requested changes

2022-09-28 23:39 UTC, JoshuaWilkes commented on pkg/eventhandler/eventhandler.go
> +		gq.Result.Grant.End = event.Time
This is not the right way to do this, the grant start and end time should not be modified after it is created.
These fields indicate the requested grant.

2022-09-28 23:39 UTC, JoshuaWilkes commented on pkg/eventhandler/eventhandler.go
> +		gq.Result.Grant.End = event.Time
The specific change that needs to be made is on the DDBKeys method of request.
There is a caculated field there which is used to sort the request into either upcoming or past

2022-09-29 06:01 UTC, JoshuaWilkes commented on web/src/components/Request.tsx
> +      {(request?.status === "PENDING" && request.grant?.status == "PENDING") ||
@meyerjrr the nesting/brackets doesn't look right here, looks like it will only show the cancel button if grant == undefined

2022-09-30 14:22 UTC, chrnorm approved these changes

2022-09-30 14:22 UTC, merged