Deprecate aws sso
common-fate/glide pull request #308
Opened 2022-10-13 04:34 UTC by meyerjrr

Adds field to enable the ability to deprecate providers
Add logic in the frontend to gracefully not allow users to use a deprecated provider
Remove permissions from access handler for over privileged sso provider implementation 
![Screen Shot 2022-10-13 at 3 00 23 pm](https://user-images.githubusercontent.com/33018450/195502402-e297511a-ee42-4c4c-8e94-a03c2b34563a.png)

2022-10-13 05:06 UTC, Eddie023 commented on accesshandler/pkg/config/providers.go
> +	Deprecated bool
nitpick: Having `is` prefix to `bool` variables is usually considered a good practice. 
```suggestion
	IsDepricated bool
```

2022-10-13 05:09 UTC, Eddie023 approved these changes

2022-10-14 00:27 UTC, JoshuaWilkes commented
To be honest I think we could just remove the aws-sso v1 provider all together.
Or at minimum, require it be removed from the deployment config before the deployment can be updated to the new version.

We need to ensure that we support deleting an access provider which has been used to create access rules and requests in the past. Could you run some checks on this before we bring this in?

2022-10-14 03:37 UTC, meyerjrr commented
> To be honest I think we could just remove the aws-sso v1 provider all together. Or at minimum, require it be removed from the deployment config before the deployment can be updated to the new version.
> 
> We need to ensure that we support deleting an access provider which has been used to create access rules and requests in the past. Could you run some checks on this before we bring this in?

Hmm my angle here was to not totally drop the support for v1, in preference of not introducing a breaking change to the configuration of the app.  Does just removing it kind of defeat the purpose of having versioned providers?
Although removing it from the codebase, would simplify things, and mitigate implementing features in the the wrong place.

I say we could include some encouraging messaging in the app to get users to remove the sso v1 from their config.

2022-10-14 10:07 UTC, chrnorm requested changes
Just marking as request changes so we can address the comments raised by @JoshuaWilkes

2022-10-14 10:08 UTC, chrnorm commented
> Does just removing it kind of defeat the purpose of having versioned providers?

@meyerjrr good question here, I see the provider versioning being more useful in future when we support community access providers. These providers will be versioned with tags in GitHub repositories, similar to how GitHub Actions are versioned.

2022-10-19 07:30 UTC, meyerjrr commented
@JoshuaWilkes @chrnorm 
I had a play around with workflows today and wanted some thoughts on how the UX should play out with a *deprecated* provider / version.

Assuming we just remove the v1 version of aws sso. and require users to remove it from their deployment config.

1. When access rules for a deprecated version exist in a deployment, what should happen when users request access?
- Filter out access rules that are using a deprecated version (dont display them in the frontend, this would need some additional config like `isDeprecated` field)
- Add validation in request access API's to fail when attempting to request access to a rule with a deprecated/removed version
- The rules still exist but they will fall back to another version, in this case will attempt to create the request with aws-sso-v2. (If this is possible)

Keen to hear your thoughts.

2022-10-19 12:02 UTC, chrnorm commented
FYI I tried deleting the AWS SSO v1 provider from an internal deployment, and users can't make requests to the access rule anymore. I think this behaviour is good, a lot better than having the access request go through and then it failing at the provisioning stage.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/17420369/196685223-9590fb86-b194-49a1-8b38-d2daa690996c.png">

2022-10-19 12:05 UTC, chrnorm commented
> When access rules for a deprecated version exist in a deployment, what should happen when users request access?

I think we should go with this option: add validation in request access API's to fail when attempting to request access to a rule with a deprecated/removed version.

We may already have this behaviour implemented. What happens if you do the following?

1. Create an Access Rule with `aws-sso@v1`
2. Delete the `aws-sso@v1` provider entirely from the codebase
3. Redeploy Granted Approvals
4. Try and make an access request to the rule

Ideally we want to fail here with a 400 Bad Request error, rather than an internal server error.

2022-10-20 01:35 UTC, meyerjrr commented
Tested and default functionality when the provider is removed is to return with the "provider not found" error as shown above.

 
![Screen Shot 2022-10-20 at 11 01 18 am](https://user-images.githubusercontent.com/33018450/196835367-5f7df269-f347-44c5-9890-2fb99a7de52a.png)
Although it will be a breaking change to bring in and we might want to inform users of this change.

2022-10-24 07:25 UTC, JoshuaWilkes approved these changes

2022-10-26 09:38 UTC, chrnorm submitted a review, later dismissed
Merge conflicts need resolving here

2022-10-28 01:27 UTC, merged