Jordi/cf 338 keyboard friendly search
common-fate/glide pull request #399
Opened 2022-12-20 07:40 UTC by jordiup

2022-12-21 07:23 UTC, meyerjrr reviewed
Looks and works good so far @jordiup. Some questions from me:
Can we make the row items clickable by mouse too? Usually that is my first initial UX intuition after searching in a search box. 
Also I remember there was a "Switch to admin" button which I was a fan of in one of the previous looms, Has that been removed?

2022-12-21 07:24 UTC, meyerjrr commented
Also Node ci tests + playwright tests are failing fyi

2022-12-21 08:09 UTC, jordiup commented
@meyerjrr, tests are now passing. Have fixed the clickable issue. Think this one is g2g 🚀

2023-01-10 07:43 UTC, JoshuaWilkes commented
On long rule names, there is a scroll on the search box.
This would probably be better if it wrapped the text instead

<img width="776" alt="image" src="https://user-images.githubusercontent.com/14214200/211491258-b5816049-a2f8-4246-b642-76c9df271093.png">

2023-01-10 08:04 UTC, JoshuaWilkes requested changes
A few changes to make but overall looking good

2023-01-10 08:04 UTC, JoshuaWilkes commented on web/src/components/nav/Navbar.tsx
> +                  <Kbd>⌘</Kbd>
We need to support users of windows and linux, at the moment this only supports mac users who have the command key.

The chakra docs use something like this, however navigator.platform is deprecated, so I would recommend using a different approach, there are a few examples online for this.
https://github.com/chakra-ui/chakra-ui-docs/blob/main/src/components/algolia-search.tsx
```typescript
const ACTION_KEY_DEFAULT = ['Ctrl', 'Control']
const ACTION_KEY_APPLE = ['⌘', 'Command']

const [actionKey, setActionKey] = React.useState<string[]>(ACTION_KEY_APPLE)
  React.useEffect(() => {
    if (typeof navigator === 'undefined') return
    const isMac = /(Mac|iPhone|iPod|iPad)/i.test(navigator.platform)
    if (!isMac) {
      setActionKey(ACTION_KEY_DEFAULT)
    }
  }, [])
```



```suggestion
                  <Kbd>⌘</Kbd>
```

2023-01-10 08:04 UTC, JoshuaWilkes commented on web/src/components/CommandPalette.tsx
> +const EditActionModal = ({
I suspect this was copied over from power editor, I think we need to rename this for the context here
```suggestion
const CommandPallet = ({
```

2023-01-11 01:29 UTC, jordiup commented
Cheers for the review Josh, think this one should now be G2G 👌 

![image](https://user-images.githubusercontent.com/21688404/211696829-ee93f176-3912-421b-b06f-7b716ee54cc6.png)
![image](https://user-images.githubusercontent.com/21688404/211696824-9b8f5d39-6b9b-4312-9b31-f0e6b621f771.png)

2023-01-11 02:23 UTC, JoshuaWilkes commented
> Cheers for the review Josh, think this one should now be G2G 👌
> 
> ![image](https://user-images.githubusercontent.com/21688404/211696829-ee93f176-3912-421b-b06f-7b716ee54cc6.png) ![image](https://user-images.githubusercontent.com/21688404/211696824-9b8f5d39-6b9b-4312-9b31-f0e6b621f771.png)

In the second image, the styling of the highlight looks to be breaking the layout, see the indent, I assume this is because its rendering as 2 elements side by side when highlighted?

2023-01-11 03:12 UTC, jordiup commented
> In the second image, the styling of the highlight looks to be breaking the layout, see the indent, I assume this is because its rendering as 2 elements side by side when highlighted?

Nice pickup Josh, fixed ✅ 
![image](https://user-images.githubusercontent.com/21688404/211709026-777d7f24-c72e-4804-b7b0-1112b9a1fb7f.png)
![image](https://user-images.githubusercontent.com/21688404/211709030-1676e787-379e-4dcf-a1f4-f76c839955e1.png)

2023-01-11 04:54 UTC, JoshuaWilkes approved these changes

2023-01-11 05:12 UTC, merged